AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Combined CFN to force RDS failover, update security group,
  wait for RDS availability, register new EC2s, and deregister old ones via Lambda.

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: RDS DB instance identifier
    Default: "dr-failover-cfn-test"

  TargetGroupUI:
    Type: String
    Description: ARN of the UI Target Group
    Default: "arn:aws:elasticloadbalancing:ap-south-1:467660529422:targetgroup/Posidex-DC-DR-UI-Test-TG/4c14bd8b597d3c33"

  TargetGroupTomcat:
    Type: String
    Description: ARN of the Tomcat Target Group
    Default: "arn:aws:elasticloadbalancing:ap-south-1:467660529422:targetgroup/Posidex-DC-DR-Tomcat-Test-TG/d6c5c09915e2a791"

  TargetGroupTokengen:
    Type: String
    Description: ARN of the Tokengen Target Group
    Default: "arn:aws:elasticloadbalancing:ap-south-1:467660529422:targetgroup/Posidex-DC-DR-Tokengen-Test-TG/57d9afda9a9c0fbe"

  NewInstances:
    Type: String
    Description: Comma-separated list of new EC2 instance IDs
    Default: "i-06956b6ce7039d983,i-0a08e5fcab036c1e5"

  OldInstances:
    Type: String
    Description: Comma-separated list of old EC2 instance IDs
    Default: "i-0de5f59fb3040547c,i-03caaa61a288402aa"

Resources:

  RDSFailoverAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSM-RDS-Failover-AutomationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowRDSAndEC2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:RebootDBInstance
                  - ec2:AuthorizeSecurityGroupIngress
                  - rds:DescribeDBInstances
                  - lambda:InvokeFunction
                Resource: "*"

  RegisterTargetsLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RegisterTargetsLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RegisterTargetsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  RegisterTargetsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RegisterTargetsAfterRDSAvailable
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt RegisterTargetsLambdaExecutionRole.Arn
      Timeout: 60
      Environment:
        Variables:
          TG_UI: !Ref TargetGroupUI
          TG_TOMCAT: !Ref TargetGroupTomcat
          TG_TOKENGEN: !Ref TargetGroupTokengen
          NEW_INSTANCES: !Ref NewInstances
          OLD_INSTANCES: !Ref OldInstances
      Code:
        ZipFile: |
          import os
          import boto3

          def handler(event, context):
              elbv2 = boto3.client('elbv2')

              TG_UI = os.environ['TG_UI']
              TG_TOMCAT = os.environ['TG_TOMCAT']
              TG_TOKENGEN = os.environ['TG_TOKENGEN']
              NEW = os.environ['NEW_INSTANCES'].split(',')
              OLD = os.environ['OLD_INSTANCES'].split(',')

              elbv2.register_targets(TargetGroupArn=TG_UI, Targets=[{'Id': NEW[0], 'Port': 8089}])
              elbv2.register_targets(TargetGroupArn=TG_TOMCAT, Targets=[{'Id': NEW[0], 'Port': 8089}, {'Id': NEW[1], 'Port': 8089}])
              elbv2.register_targets(TargetGroupArn=TG_TOKENGEN, Targets=[{'Id': NEW[0], 'Port': 2405}])

              elbv2.deregister_targets(TargetGroupArn=TG_UI, Targets=[{'Id': OLD[0], 'Port': 8089}])
              elbv2.deregister_targets(TargetGroupArn=TG_TOMCAT, Targets=[{'Id': OLD[0], 'Port': 8089}, {'Id': OLD[1], 'Port': 8089}])
              elbv2.deregister_targets(TargetGroupArn=TG_TOKENGEN, Targets=[{'Id': OLD[0], 'Port': 2405}])

              return {"status": "targets updated"}

  RDSFailoverSSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: RDS-Force-Failover
      DocumentType: Automation
      DocumentFormat: YAML
      UpdateMethod: NewVersion
      Content:
        description: RDS failover + SG update + target refresh
        schemaVersion: '0.3'
        assumeRole: '{{ AutomationAssumeRole }}'
        parameters:
          DBInstanceIdentifier:
            type: String
            description: RDS DB Instance Identifier
          AutomationAssumeRole:
            type: String
            description: IAM Role for Automation
        mainSteps:
          - name: RebootRDS
            action: aws:executeAwsApi
            inputs:
              Service: rds
              Api: RebootDBInstance
              DBInstanceIdentifier: '{{ DBInstanceIdentifier }}'
              ForceFailover: true

          - name: AddIngressForDR1
            action: aws:executeAwsApi
            inputs:
              Service: ec2
              Api: AuthorizeSecurityGroupIngress
              GroupId: sg-01fe63d5cf1d626e9
              IpPermissions:
                - IpProtocol: tcp
                  FromPort: 3306
                  ToPort: 3306
                  IpRanges:
                    - CidrIp: 172.28.7.144/32
                      Description: PosidexDR-test-1

          - name: AddIngressForDR2
            action: aws:executeAwsApi
            inputs:
              Service: ec2
              Api: AuthorizeSecurityGroupIngress
              GroupId: sg-01fe63d5cf1d626e9
              IpPermissions:
                - IpProtocol: tcp
                  FromPort: 3306
                  ToPort: 3306
                  IpRanges:
                    - CidrIp: 172.28.7.181/32
                      Description: PosidexDR-test-2

          - name: WaitForRDSAvailable
            action: aws:waitForAwsResourceProperty
            inputs:
              Service: rds
              Api: DescribeDBInstances
              DBInstanceIdentifier: '{{ DBInstanceIdentifier }}'
              PropertySelector: '$.DBInstances[0].DBInstanceStatus'
              DesiredValues:
                - available

          - name: InvokeRegisterLambda
            action: aws:invokeLambdaFunction
            inputs:
              FunctionName: RegisterTargetsAfterRDSAvailable
              Payload: '{"DBInstanceIdentifier":"{{ DBInstanceIdentifier }}"}'

Outputs:
  SSMDocumentName:
    Value: !Ref RDSFailoverSSMDocument
  AutomationRoleArn:
    Value: !GetAtt RDSFailoverAutomationRole.Arn
  LambdaFunctionName:
    Value: !Ref RegisterTargetsLambda